# src/main/resources/application-prod.yml
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useSSL=false&serverTimezone=UTC
    username: root 
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  thymeleaf:
    cache: true
    mode: HTML
  sql:
    init:
      mode: never

server:
  port: ${PORT:8080}
  servlet:
    context-path: /smartstock
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

logging:
  level:
    com.smartstock: INFO
    org.hibernate: WARN
    org.springframework.security: WARN
  file:
    name: logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Configuración de seguridad para producción
security:
  basic:
    enabled: false