spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: smartstock

---
# Configuración de desarrollo
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/smartstock?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false

---
# Configuración de producción (se activa en Azure)
spring:
  config:
    activate:
      on-profile: prod
  # La configuración específica está en application-prod.yml