name: Deploy SmartStock to Azure

on:
  push:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: 'smartstock-app-miguelhc'
  JAVA_VERSION: '17'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn clean package -DskipTests
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: smartstock-app
        path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: 'production'
    steps:
    - name: Download JAR
      uses: actions/download-artifact@v4
      with:
        name: smartstock-app
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v3
      with:
        app-name: smartstock-app-miguelhc
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: '*.jar'
